<div id="view-content">
    <p><h6>Please insert a new programming language. All fields are required.</h6></p>
    <form class="nice" action="<?= $this->form->getAction(); ?>" method="<?= $this->form->getMethod(); ?>" >
    <table class="list-languages">
        <tr>
            <td><b>Language Name</b></td>
            <td><?php echo $this->form->getElement('language_name'); ?></td>
        </tr>
        <tr>
            <td><b>Description</b></td>
            <td><?php echo $this->form->getElement('language_description'); ?></td>
        </tr>
        <tr>
            <td colspan="2"><?php echo $this->form->getElement('submit'); ?>&nbsp;&nbsp;&nbsp;or&nbsp;&nbsp;&nbsp;<a href="/crud/">Cancel</a></td>
        </tr>
    </table>
    </form>
</div>