<div id="view-content">
    <div class="container">
        <div class="row">
            <div class="twelve columns">
                
                    This project was part of a job application, whose goal is to implement a basic CRUD interface (create, read, update
                    and delete), using Zend Framework. For more details, please read the README file.<br/><br/>
                    I'm a Web Designer and PHP Developer, with a degree in Computer Science. My passion for the web led me to an online career,
                    with main focus on developing professional websites and e-commerce web applications.<br/><br/>
                    If you would like to send me a work inquiry, please visit the following link: http://www.joaoluis.net/contacto.php <br/><br/>
                    Thank you for visiting my github profile.
            </div>
        </div>
    </div>
</div>