<div id="view-content">
    <?php
        if(count($this->results)>0){
            ?>
            <table class="list-languages" id="searchResults">
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Update</th>
                    <th>Delete</th>
                </tr>
                <?php
                foreach($this->results AS $pl){
                    ?>
                    <tr>
                        <td><?php echo $pl->language_name; ?></td>
                        <td><?php echo $pl->language_description; ?></td>
                        <td class="icon"><a href="/crud/edit?id=<?php echo $pl->id; ?>"><img src="/images/icons/layout-design.png" /></a></td>
                        <td class="icon"><a href="/crud/delete?id=<?php echo $pl->id; ?>"><img src="/images/icons/cross.png" /></a></td>
                    </tr>
                    <?
                }
                ?>
            </table>
        <?
        }
        else {
            ?>
            <p class="p20">No results to display... Please, try again.</p>
            <?
        }
    ?>
</div>